package com.game.roguelike.entity

data class BlessingEffects(
    var critChance: Float = 0f,
    var critMultiplier: Float = 2f,
    var attackRangeBonus: Float = 0f,
    var slowOnHit: Float = 0f,
    var freezeDuration: Float = 0f,
    var freezeDamageMultiplier: Float = 1f,
    var lowHpDamageMultiplier: Float = 1f,
    var bossDamageBonus: Float = 0f,
    var killHealAmount: Float = 0f,
    var dashInvincibleExtension: Float = 0f,
    var dashSpeedBoostDuration: Float = 0f,
    var dashSlowNearby: Float = 0f,
    var lightningBounce: Boolean = false,
    var critHealAmount: Float = 0f,
    var allDamageBonus: Float = 0f,
    var comboAlwaysCrit: Boolean = false,
    var supportFreeze: Boolean = false,
    var hasSummon: Boolean = false,
    var knifeExplosive: Boolean = false,
    var knifeCount: Int = 1,
    var warCryDamageBonus: Float = 0f,
    var athenaShieldActive: Boolean = false,
    var athenaShieldCooldown: Float = 10f,
    var shieldInvincibleDuration: Float = 0f,
    var duoHeartLightning: Boolean = false,
    var duoThunderShield: Boolean = false,
    var duoBloodHeart: Boolean = false,
    var duoSpeedShield: Boolean = false,
    var duoIceBlood: Boolean = false,
    var duoDeathLove: Boolean = false,
    var duoJudgement: Boolean = false
)
