package com.game.roguelike.core

enum class GameState {
    MENU,
    INTRO_STORY,
    BLESSING_STORY,
    PLAYING,
    SHOP,
    EVENT,
    BLESSING_SELECT,
    LAYER_TRANSITION,
    BOSS_ENTRANCE,
    BOSS_RELIC_STORY,
    PLAYER_DEATH,
    FAILURE_STORY,
    GAME_OVER,
    VICTORY,
    ENDING_STORY,
    MULTIPLAYER_LOBBY,
    ROOM_LIST,
    ROOM_WAITING,
    OPTIONS,
    LOAD_SAVE_CONFIRM,
    SAVE_GAME_CONFIRM,
    EXIT_CONFIRM
}

enum class LayerId {
    TARTARUS,
    ASPHODEL,
    ELYSIUM
}

enum class Direction {
    UP, DOWN, LEFT, RIGHT,
    UP_LEFT, UP_RIGHT, DOWN_LEFT, DOWN_RIGHT
}
